name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      env:
        VITE_HONEYBADGER_API_KEY: ${{ secrets.VITE_HONEYBADGER_API_KEY }}
        VITE_ENVIRONMENT: production
        
    - name: Run tests (if any)
      run: npm run test --if-present
      
    # If you're deploying to Vercel, this step is optional
    # as Vercel will handle deployment automatically
    - name: Deploy to Vercel
      uses: vercel/action@v1
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
      env:
        VITE_HONEYBADGER_API_KEY: ${{ secrets.VITE_HONEYBADGER_API_KEY }}
        VITE_ENVIRONMENT: production
